[package]
name = "prune-lang"
version = "0.2.4"
authors = ["Anton Ping <antonping1999@gmail.com>"]
edition = "2024"
description = "Prune is a constraint logic programming language with branching heuristic."
readme = "README.md"
repository = "https://github.com/antonping/prune-lang"
license = "Apache-2.0"
keywords = ["logic-programming", "dsl", "prolog", "kanren", "smt"]
categories = ["command-line-utilities", "compilers"]

[[bin]]
name = "prune"
path = "src/main.rs"

[dependencies]
logos = "0.16.1"
snailquote = "0.3.1"
itertools = "0.15.0"
rand = "0.10.2"
easy-smt = "0.3.2"
clap = { version = "4.6.2", features = ["derive"] }

[dev-dependencies]
criterion = "0.8.2"
insta = { version = "1.48.0", features = ["yaml"] }

[[bench]]
name = "test_benches"
harness = false
